Algoritmo "idades"

Var
     nome1, nome2 : caractere
     idade1, idade2 : inteiro
     media : real
Inicio

      escreva("digite o seu nome: ")
      leia(nome1)
      escreva(" digite sua idade: ")
      leia(idade1)
      escreva("digite o seu nome: ")
      leia(nome2)
      escreva(" digite sua idade: ")
      leia(idade2)
      
      media <- (idade1 + idade2) / 2
      
      escreva(" A idade media de ", nome1 , " e " , nome2 , " eh de ", media)


Fimalgoritmo