Algoritmo "Pagamento"

Var
 Nome: caracter
 pagamento, valorHora: real
 horasTrabalhadas: inteiro

Inicio

 escreva("digite o nome: ")
 leia(nome)
 escreva(" digite o valor da hora: ")
 leia(valorHora)
 escreva("digite a quantidade de horas trabalhada: ")
 leia(horasTrabalhadas)
 
pagamento <- valorHora * horastrabalhadas

escreva(" o Pagamento para ", nome, " deve ser: ", pagamento)

Fimalgoritmo