Algoritmo "terreno"

Var
largura, comprimento, metroQuadrado, preco, area : real

Inicio

escreva("digite a largura do terreno: ")
leia(largura)

escreva("digite o comprimento do terreno: ")
leia(comprimento)

escreva("digite o valor do metro quadrado: ")
leia(preco)

preco <- comprimento * preco
area  <- largura * comprimento

escreval("Area do terreno = ", area)
escreva("Preco do terreno = ", preco)

Fimalgoritmo